import emailjs from '@emailjs/browser';

/**
 * WHY EMAILJS:
 * - Extremely fast integration (no backend mail server setup needed like Nodemailer/SendGrid)
 * - Great for MVPs, hackathons, and serverless architectures
 *
 * SECURITY LIMITATION:
 * - We are sending a dynamically generated password natively via email. 
 *   Passwords should ideally never be transmitted in plain text.
 *
 * PRODUCTION UPGRADE:
 * - A secure system should NOT generate or email passwords.
 * - Instead: Generate a secure, expiring JWT "Reset Token", save the token hash to the user model.
 * - Email a magic link (e.g., https://yourdomain.com/setup-password?token=abc123xyz)
 * - The user clicks the link, sets their own password, and only the bcrypt hash is ever stored.
 */

// NOTE: Replace these with your actual EmailJS credentials
const SERVICE_ID = 'service_obwt0we';
const TEMPLATE_ID = 'template_0c6ni78';
const PUBLIC_KEY = 'MTyXhA9BhWhaujrvF';

/**
 * Sends a welcome email containing generated credentials to a newly onboarded user.
 * 
 * @param {Object} user - The user object containing name, email, and role.
 * @param {string} tempPassword - The secure temporary password generated by the backend.
 * @returns {Promise<Object>} The EmailJS response.
 */
export async function sendWelcomeEmail(user, tempPassword) {
  // Ensure we don't crash if credentials aren't set up yet
  if (SERVICE_ID === 'YOUR_SERVICE_ID') {
    console.warn('⚠️ EmailJS not configured. Please add your Service ID, Template ID, and Public Key to emailService.js');
    console.log('--- MOCK EMAIL CONTENT ---');
    console.log(`To: ${user.email}\nName: ${user.name}\nPassword: ${tempPassword}\nRole: ${user.role}\nLogin URL: http://localhost:5173/login`);
    console.log('--------------------------');
    return { status: 200, text: 'Simulated OK' }; // simulate success for demo
  }

  const templateParams = {
    to_email: user.email,
    name: user.name,
    EMAIL: user.email,
    PASSWORD: tempPassword,
    ROLE: user.role,
    login_url: 'http://localhost:5173/login',
  };

  try {
    const response = await emailjs.send(
      SERVICE_ID,
      TEMPLATE_ID,
      templateParams,
      PUBLIC_KEY
    );
    return response;
  } catch (error) {
    console.error('EmailJS Error:', error);
    throw error;
  }
}
